[package]
name = "text-editor"
version = "0.1.0"
edition = "2018"

[dependencies]
speedy2d = "1.2.0"
derivative = "2.2.0"
unicode-normalization = "0.1.19"


[profile.release]
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"