[package]
name = "text-editor"
version = "0.2.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
speedy2d = "1.8.0"

[profile.release]
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
